### PR TITLE
JSON response in request to Prestashop API. And update code to PSR-1 and PSR-2

### PR DESCRIPTION
**Pull request by m-lopez-f**

### CODE REVIEW

**Comment by m-lopez-f** [comment]
Update min version, because JSON response only exist on 1.6 or 1.7

**Comment by bnowak** [comment]
+1
IMHO handling JSON format is one of the basic thing which api client should have.
I need this in my project because when api client returns SimpleXMLElement it can't be serialized, so I can't cache it to redis.
Please merge it.

**Comment by GC-Mik** [comment]
totally agree +1

**Comment by bartekbujak** [comment]
+1

**Comment by MichelDiz** [comment]
It would be better to change the API to GraphQL. It would be universally compatible and malleable.

**Comment by gralec99** [comment]
Awesome feature, I also need that for my project

**Comment by jacmgh** [comment]
I also need it, so merging this PR would be much appreciated.

**Comment by incaib** [comment]
Hola. Estoy trabajando en una aplicación de escritorio con Python y trabajaba directamente cambiando la base de datos de PrestaShop, con la dificultad de los cambios entre versiones. He estado leyendo y leí sobre WebService de PrestaShop, luego pensé que perdí mucho tiempo, aunque bueno aprendo a conocer la base de datos. Terminando... Algún guía buena para conocer WebService?

**Comment by incaib** [comment]
Hola. Estoy trabajando en una aplicación de escritorio con Python y trabajaba directamente cambiando la base de datos de PrestaShop, con la dificultad de los cambios entre versiones. He estado leyendo y leí sobre WebService de PrestaShop, luego pensé que perdí mucho tiempo, aunque bueno aprendo a conocer la base de datos. Terminando... Algún guía buena para conocer WebService?

**Comment by m-lopez-f** [comment]
@incaib in this case, http://doc.prestashop.com/display/PS16/Using+the+PrestaShop+Web+Service
its a official documentation of web service.

**Comment by incaib** [comment]
Is compatible WebService from PS16 with 17. Thanks!! Good link.

**Comment by ariaenggar** [comment]
How's this going? I still need the JSON response.

**Comment by matks** [comment]
Hi @m-lopez-f your contribution is great but it seems stale. Are you still interested in this ?

**Comment by m-lopez-f** [comment]
Yes, I return on project on next days.

**Comment by PierreRambaud** [comment]
Hi @m-lopez-f ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
