### PR TITLE
Composer requires license identifier, no title+url

### PR DESCRIPTION
**Pull request by acusti**
Here’s the [full list](https://spdx.org/licenses/) of license identifiers from which I took `"OSL-3.0"`

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR.

Best regards.

**Comment by acusti** [comment]
:+1: Thanks to you!

**Comment by jeromenadaud** [comment]
;-) tomorrow I check all pending PR and merge dev into master, in order to get a unique branch

**Comment by acusti** [comment]
Hope this doesn’t come too late; I just tried using the library with Composer and realized that `composer.json` still needs the `autoload` property to make sure Composer is able to autoload it into a project.

**Pull request merged**
